name: CI

env:
  JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xmx8G -Xss4M -XX:+UseG1GC # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
  JVM_OPTS: -XX:+PrintCommandLineFlags -Xmx8G -Xss4M -XX:+UseG1GC # for Java 8 only (sadly, it is not modern enough for JDK_JAVA_OPTIONS)
  NODE_OPTIONS: --max_old_space_size=6144

on:
  pull_request:
  push:
    branches: ['main']
  release:
    types:
      - published

jobs:
  lint:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Lint code
        run: sbt fmtCheck fixCheck

  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '17']
        scala: ['2.12.17', '2.13.10', '3.2.2']
    steps:
    - name: Checkout current branch
      uses: actions/checkout@v3.3.0
    - name: Setup Java
      uses: actions/setup-java@v3.10.0
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: 'sbt'
    - name: Install libuv
      run: sudo apt-get update && sudo apt-get install -y libuv1-dev
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 9
    - name: Run tests
      run: sbt ++${{ matrix.scala }} test

  publish:
    runs-on: ubuntu-20.04
    timeout-minutes: 45
    needs: [build,lint]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3.3.0
      - name: Setup Java
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: 8
          cache: 'sbt'
      - name: Install libuv
        run: sudo apt-get update && sudo apt-get install -y libuv1-dev
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 9
      - run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
